// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;
import ballerina/mime;

# Barcode APIs let you generate barcode images, and recognize values from images of barcodes.
public isolated client class Client {
    final http:Client clientEp;
    final readonly & ApiKeysConfig apiKeyConfig;
    # Gets invoked to initialize the `connector`.
    #
    # + apiKeyConfig - API keys for authorization 
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ApiKeysConfig apiKeyConfig, ConnectionConfig config =  {}, string serviceUrl = "https://api.cloudmersive.com/barcode") returns error? {
        http:ClientConfiguration httpClientConfig = {httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
        self.apiKeyConfig = apiKeyConfig.cloneReadOnly();
    }

    # Lookup EAN barcode value, return product data
    #
    # + headers - Headers to be sent with the request 
    # + payload - Barcode value 
    # + return - Product data for the matched barcode 
    remote isolated function lookupEanBarcode(string payload, map<string|string[]> headers = {}) returns BarcodeLookupResponse|error {
        string resourcePath = string `/lookup/ean`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Scan and recognize an image of a barcode
    #
    # + headers - Headers to be sent with the request 
    # + return - Recognized value and type of the barcode in the image 
    remote isolated function scanBarcodeImage(ScanBarcodeImageRequest payload, map<string|string[]> headers = {}) returns BarcodeScanResult|error {
        string resourcePath = string `/scan/image`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(check jsondata:toJson(payload).ensureType());
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Advanced AI scan and recognition of an image of one or more barcodes of any type
    #
    # + headers - Headers to be sent with the request 
    # + return - Recognized barcodes found in the image 
    remote isolated function scanBarcodeImageAdvanced(ScanBarcodeImageRequest payload, map<string|string[]> headers = {}) returns BarcodeAdvancedScanResult|error {
        string resourcePath = string `/scan/image/advanced`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(check jsondata:toJson(payload).ensureType());
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Advanced AI scan and recognition of an image of one or more QR barcodes
    #
    # + headers - Headers to be sent with the request 
    # + return - Recognized QR barcodes found in the image 
    remote isolated function scanQrBarcodeImageAdvanced(ScanBarcodeImageRequest payload, ScanQrBarcodeImageAdvancedHeaders headers = {}) returns BarcodeScanQRAdvancedResult|error {
        string resourcePath = string `/scan/image/advanced/qr`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(check jsondata:toJson(payload).ensureType());
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Advanced AI scan and recognition of an image of one or more QR barcodes as a Batch Job
    #
    # + headers - Headers to be sent with the request 
    # + return - Identifier of the created barcode batch job 
    remote isolated function createQrScanBatchJob(ScanBarcodeImageRequest payload, CreateQrScanBatchJobHeaders headers = {}) returns BarcodeBatchJobResult|error {
        string resourcePath = string `/batch-job/scan/image/advanced/qr`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        mime:Entity[] bodyParts = check createBodyParts(check jsondata:toJson(payload).ensureType());
        request.setBodyParts(bodyParts);
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Get the status and result of a Barcode Batch Job
    #
    # + headers - Headers to be sent with the request 
    # + queries - Queries to be sent with the request 
    # + return - Status and, once completed, result of the barcode batch job 
    remote isolated function getBatchJobStatus(map<string|string[]> headers = {}, *GetBatchJobStatusQueries queries) returns BarcodeBatchJobStatusResult|error {
        string resourcePath = string `/batch-job/status`;
        resourcePath = resourcePath + check getPathForQueryParam(queries);
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        return self.clientEp->get(resourcePath, httpHeaders);
    }

    # Generate a QR code barcode as PNG file
    #
    # + headers - Headers to be sent with the request 
    # + payload - QR code text to convert into the QR code barcode 
    # + return - PNG image of the generated QR code 
    remote isolated function generateQrCode(string payload, GenerateQrCodeHeaders headers = {}) returns byte[]|error {
        string resourcePath = string `/generate/qrcode`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generate a UPC-A code barcode as PNG file
    #
    # + headers - Headers to be sent with the request 
    # + payload - UPC-A barcode value to generate from 
    # + return - PNG image of the generated UPC-A barcode 
    remote isolated function generateUpcABarcode(string payload, GenerateUpcABarcodeHeaders headers = {}) returns byte[]|error {
        string resourcePath = string `/generate/upc-a`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generate a UPC-E code barcode as PNG file
    #
    # + headers - Headers to be sent with the request 
    # + payload - UPC-E barcode value to generate from 
    # + return - PNG image of the generated UPC-E barcode 
    remote isolated function generateUpcEBarcode(string payload, GenerateUpcEBarcodeHeaders headers = {}) returns byte[]|error {
        string resourcePath = string `/generate/upc-e`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generate a EAN-13 code barcode as PNG file
    #
    # + headers - Headers to be sent with the request 
    # + payload - Barcode value to generate from 
    # + return - PNG image of the generated EAN-13 barcode 
    remote isolated function generateEan13Barcode(string payload, GenerateEan13BarcodeHeaders headers = {}) returns byte[]|error {
        string resourcePath = string `/generate/ean-13`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generate a EAN-8 code barcode as PNG file
    #
    # + headers - Headers to be sent with the request 
    # + payload - Barcode value to generate from 
    # + return - PNG image of the generated EAN-8 barcode 
    remote isolated function generateEan8Barcode(string payload, GenerateEan8BarcodeHeaders headers = {}) returns byte[]|error {
        string resourcePath = string `/generate/ean-8`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Generate a Code 128 barcode as PNG file
    #
    # + headers - Headers to be sent with the request 
    # + payload - Barcode value to generate from 
    # + return - PNG image of the generated Code 128 barcode 
    remote isolated function generateCode128Barcode(string payload, GenerateCode128BarcodeHeaders headers = {}) returns byte[]|error {
        string resourcePath = string `/generate/code-128`;
        map<anydata> headerValues = {...headers};
        headerValues["Apikey"] = self.apiKeyConfig.apikey;
        map<string|string[]> httpHeaders = http:getHeaderMap(headerValues);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }
}
