// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# Result of the advanced barcode scan
public type BarcodeAdvancedScanResult record {
    # Number of barcodes read
    @jsondata:Name {value: "BarcodeCount"}
    int:Signed32 barcodeCount?;
    # Results of performing the barcode scan operation
    @jsondata:Name {value: "ResultBarcodes"}
    BarcodeAdvancedResultItem[] resultBarcodes?;
    # Error message if any
    @jsondata:Name {value: "ErrorMessage"}
    string errorMessage?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Represents the Headers record for the operation: generateUpcEBarcode
public type GenerateUpcEBarcodeHeaders record {
    # Optional: width of the barcode in pixels.  Minimum value of 10
    int width?;
    # Optional: show text label on the image of the barcode value, default is true
    boolean includeLabel?;
    # Optional: height of the barcode in pixels.  Minimum value of 10
    int height?;
};

# Represents the Headers record for the operation: generateEan8Barcode
public type GenerateEan8BarcodeHeaders record {
    # Optional: width of the barcode in pixels.  Minimum value of 10
    int width?;
    # Optional: show text label on the image of the barcode value, default is true
    boolean includeLabel?;
    # Optional: height of the barcode in pixels.  Minimum value of 10
    int height?;
};

# Matching product for the input barcode
public type ProductMatch record {
    # EAN code for the product
    @jsondata:Name {value: "EAN"}
    string eAN?;
    # Title of the product
    @jsondata:Name {value: "Title"}
    string title?;
};

# Result of the barcode scan
public type BarcodeScanResult record {
    # The barcode text
    @jsondata:Name {value: "RawText"}
    string rawText?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # The type of the barcode; possible values are AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB
    @jsondata:Name {value: "BarcodeType"}
    string barcodeType?;
};

# Advanced barcode scan result instance
public type BarcodeAdvancedResultItem record {
    # The barcode text
    @jsondata:Name {value: "RawText"}
    string rawText?;
    # Type of the barcode; supported barcode types include AZTEC, CODABAR, CODE_39, CODE_93, CODE_128, DATA_MATRIX, EAN_8, EAN_13, ITF, MAXICODE, PDF_417, QR_CODE, RSS_14, RSS_EXPANDED, UPC_A, UPC_E, All_1D, UPC_EAN_EXTENSION, MSI, PLESSEY, IMB
    @jsondata:Name {value: "BarcodeType"}
    string barcodeType?;
};

# Result of performing a barcode lookup
public type BarcodeLookupResponse record {
    # Resulting product matches for the input barcode
    @jsondata:Name {value: "Matches"}
    ProductMatch[] matches?;
    # True if operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Represents the Headers record for the operation: scanQrBarcodeImageAdvanced
public type ScanQrBarcodeImageAdvancedHeaders record {
    # Optional, preprocessing mode, default is 'Auto'.  Possible values are None (no preprocessing of the image), SmoothEdges, SmoothEdgesPlus, and Auto (automatic image enhancement of the image - including automatic unrotation of the image - before OCR is applied; this is recommended).  Set this to 'None' if you do not want to use automatic image unrotation and enhancement.  Set to SmoothEdges to smooth harsh edges in the input image to enhance recognition accuracy.  Set to SmoothEdgesPlus to smooth harsh edges to a higher degree
    string preprocessing?;
    # Optional, recognitionMode mode, default is 'Advanced'.  Possible values are Advanced, and Advanced2 which provides the most advanced available barcode recognition
    string recognitionMode?;
};

# Represents the Headers record for the operation: createQrScanBatchJob
public type CreateQrScanBatchJobHeaders record {
    # Optional, preprocessing mode, default is 'Auto'.  Possible values are None (no preprocessing of the image), SmoothEdges, SmoothEdgesPlus, and Auto (automatic image enhancement of the image - including automatic unrotation of the image - before OCR is applied; this is recommended).  Set this to 'None' if you do not want to use automatic image unrotation and enhancement.  Set to SmoothEdges to smooth harsh edges in the input image to enhance recognition accuracy.  Set to SmoothEdgesPlus to smooth harsh edges to a higher degree
    string preprocessing?;
    # Optional, recognitionMode mode, default is 'Advanced'.  Possible values are Advanced, and Advanced2 which provides the most advanced available barcode recognition
    string recognitionMode?;
};

public type ScanBarcodeImageRequest record {
    # Image file to perform the operation on.  Common file formats such as PNG, JPEG are supported
    record {byte[] fileContent; string fileName;} imageFile;
};

# Represents the Queries record for the operation: getBatchJobStatus
public type GetBatchJobStatusQueries record {
    # Job ID for the batch job to get the status of
    @http:Query {name: "AsyncJobID"}
    string asyncJobID;
};

# Result of checking on the status of a barcode batch job
public type BarcodeBatchJobStatusResult record {
    @jsondata:Name {value: "QRScanResult"}
    BarcodeScanQRAdvancedResult qRScanResult?;
    # Job ID
    @jsondata:Name {value: "AsyncJobID"}
    string asyncJobID?;
    # Error message (if any)
    @jsondata:Name {value: "ErrorMessage"}
    string errorMessage?;
    # True if the operation to check the status of the job was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
    # Returns the job status of the Async Job, if applicable.  Possible states are STARTED and COMPLETED
    @jsondata:Name {value: "AsyncJobStatus"}
    string asyncJobStatus?;
};

# Result of the advanced QR barcode scan
public type BarcodeScanQRAdvancedResult record {
    # Number of barcodes read
    @jsondata:Name {value: "BarcodeCount"}
    int:Signed32 barcodeCount?;
    # Results of performing the QR barcode scan operation
    @jsondata:Name {value: "ResultBarcodes"}
    BarcodeQRResultItem[] resultBarcodes?;
    # Error message if any
    @jsondata:Name {value: "ErrorMessage"}
    string errorMessage?;
    # True if the operation was successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Represents the Headers record for the operation: generateQrCode
public type GenerateQrCodeHeaders record {
    # Optional: width of the barcode in pixels.  Minimum value of 10
    int width?;
    # Optional: height of the barcode in pixels.  Minimum value of 10
    int height?;
};

# QR barcode instance
public type BarcodeQRResultItem record {
    # The barcode text
    @jsondata:Name {value: "RawText"}
    string rawText?;
};

# Result of creating a barcode batch job
public type BarcodeBatchJobResult record {
    # When creating a job, an Async Job ID is returned.  Use the GetAsyncJobStatus API to check on the status of this job using the AsyncJobID and get the result when it finishes
    @jsondata:Name {value: "AsyncJobID"}
    string asyncJobID?;
    # True if successful, false otherwise
    @jsondata:Name {value: "Successful"}
    boolean successful?;
};

# Represents the Headers record for the operation: generateCode128Barcode
public type GenerateCode128BarcodeHeaders record {
    # Optional: width of the barcode in pixels.  Minimum value of 10
    int width?;
    # Optional: show text label on the image of the barcode value, default is true
    boolean includeLabel?;
    # Optional: height of the barcode in pixels.  Minimum value of 10
    int height?;
};

# Represents the Headers record for the operation: generateEan13Barcode
public type GenerateEan13BarcodeHeaders record {
    # Optional: width of the barcode in pixels.  Minimum value of 10
    int width?;
    # Optional: show text label on the image of the barcode value, default is true
    boolean includeLabel?;
    # Optional: height of the barcode in pixels.  Minimum value of 10
    int height?;
};

# Provides API key configurations needed when communicating with a remote HTTP endpoint.
public type ApiKeysConfig record {|
    # API Key Authentication
    @display {label: "", kind: "password"}
    string apikey;
|};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# Represents the Headers record for the operation: generateUpcABarcode
public type GenerateUpcABarcodeHeaders record {
    # Optional: width of the barcode in pixels.  Minimum value of 10
    int width?;
    # Optional: show text label on the image of the barcode value, default is true
    boolean includeLabel?;
    # Optional: height of the barcode in pixels.  Minimum value of 10
    int height?;
};
